# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M.xci
# IP: The module: 'clk_wiz_100M_to_400M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100M_to_400M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100M_to_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100M_to_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M.xci
# IP: The module: 'clk_wiz_100M_to_400M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100M_to_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100M_to_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_100M_to_400M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
