# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.cache/wt} [current_project]
set_property parent.project_path {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_output_repo {d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/CLK_CH_A_generator.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/CLK_D_A_generator.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/CLK_LATCH_A_generator.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/PSI_stem.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/new/SPI.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/new/clk_booster.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/dac_reset.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/programmable_3_phase_clock.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/starter_ABC.v}
  D:/Neurostimulation/board_test_programmable_A_with_ethernet_mannul_channel_change/board_test_programmable_A_with_ethernet.srcs/sources_1/new/structre_A.v
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/structure_B.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/structure_clocks.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/two_phase_generator.v}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/new/board_test.v}
}
read_vhdl -library xil_defaultlib {
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/imports/hdl/add_crc32.vhd}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/imports/hdl/add_preamble.vhd}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/imports/hdl/byte_data.vhd}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/imports/hdl/gigabit_test.vhd}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/imports/hdl/rgmii_rx.vhd}
  {D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/imports/imports/hdl/rgmii_tx.vhd}
}
read_ip -quiet {{D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M.xci}}
set_property used_in_implementation false [get_files -all {{d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M_board.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M.xdc}}]
set_property used_in_implementation false [get_files -all {{d:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/sources_1/ip/clk_wiz_100M_to_400M/clk_wiz_100M_to_400M_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/constrs_1/new/board_test.xdc}}
set_property used_in_implementation false [get_files {{D:/Neurostimulation/One Channel Demo/board_test_programmable_A_with_ethernet.srcs/constrs_1/new/board_test.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top board_testBC -part xc7a200tsbg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef board_testBC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file board_testBC_utilization_synth.rpt -pb board_testBC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
