@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue May 29 12:01:42 -0400 2018
REM SW Build 2188600 on Wed Apr  4 18:40:38 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim ABC_switch_tb_behav -key {Behavioral:sim_1:Functional:ABC_switch_tb} -tclbatch ABC_switch_tb.tcl -view D:/Kannect/board_test_programmable_A_with_ethernet_mannul_channel_change/ABC_switch_tb_behav.wcfg -view D:/Kannect/board_test_programmable_A_with_ethernet_mannul_channel_change/dac_Test.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
